"""empty message

Revision ID: e9f2acd455a1
Revises: b617fba8cfb2
Create Date: 2024-08-22 13:42:47.978272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f2acd455a1'
down_revision = 'b617fba8cfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roleType', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('country')
        batch_op.drop_column('address')
        batch_op.drop_column('business_name')
        batch_op.drop_column('roleType')

    # ### end Alembic commands ###
